### ISSUE TITLE
Popup window cannot be opened

### ISSUE THREAD

**Issue by fssdlyl001** [ebailey78/shinyBS#14]
I have added a popup window in my app with "bsModal" and "toggleModal" function but cannot open it by now.
Error as follows:
Error in (structure(function (input, output, session)  : 
  could not find function "toggleModal"

**Comment by ebailey78** [comment]
Did you update to shiny v0.11? With that update shiny moved from Bootstrap 2 to Bootstrap 3 as the web framework. This has completely broken shinyBS. I am working on updates but it may take a while. Sorry for any inconvenience.
