### ISSUE TITLE
bsModal works with shinydashboard but not when tabItems / tabItem are utilized

### ISSUE THREAD

**Issue by AdrianAntico** [ebailey78/shinyBS#141]
@ebailey78 Not sure if you're aware (or if I'm just doing this wrong) but I can get a bsModal() working with shinydashboard but when I incorporate shinydashboard::tabItems() and shinydashboard::tabItem(), the bsModal() won't activate when it otherwise would without the tabItems and tabItem.

If you have encountered this, is there a workaround or am I out of luck for using bsModal()?

Thanks for you time

**Comment by sanjmeh** [comment]
Adrian did you get any update or workaround?

**Comment by AdrianAntico** [comment]
I went with an alternative approach. No worries
