### ISSUE TITLE
bsTooltip issues with Shiny 0.11 and shinyBS 0.50

### ISSUE THREAD

**Issue by dwahman** [ebailey78/shinyBS#15]
Noticing 2 issues with bsTooltip with the latest upgrades:
1.  For selectInput, if selectize is set to "true", then the tooltip will not show.  Turning selectize to "false" makes the tooltip appear. 
2. If position is set to "right", tooltip box is very narrow.  Any other position (top, left, bottom) and a wider box is created.

**Comment by ebailey78** [comment]
Thanks for the feedback. I've fixed the issue with tooltips not showing up on selectize inputs. As far as skinny tooltips are concerned that is an issue with how selectize inputs are created. I think you can overcome it by using the new `options` argument. Setting `options = list(container = 'body')` should make the tooltip wider.

**Comment by dwahman** [comment]
Thank you for fixing the issue on the tooltips not showing up on selectize inputs.

As far as the narrow tooltip for “right” positioning, this is occurring with all input types in my current application (e.g., sliders, check box groups, selectInputs).  The tooltips actually look normal if running in the RStudio browser but appear narrow with Chrome.  I tried to implement your suggestion with the options, but this did not resolve the issue.  I’ll keep investigating.

Again, thank you for creating this package.

**Comment by ebailey78** [comment]
Hmm, That’s interesting. I tested it in firefox and chrome and it seemed to fix the problem. If you can provided me with some example code and a screenshot I will look into it more.

**Comment by dwahman** [comment]
Eric,

Attached is a portion of my code with several tooltips.  The tooltips generated to the right are narrow for me when I view in Chrome, but the view as a normal width when using the RStudio browser.

Let me know if you get the same.

Thanks,
Dave
