### ISSUE TITLE
bsPopover HTML content

### ISSUE THREAD

**Issue by akaever** [ebailey78/shinyBS#22]
Hi,

Thank you for your work.

I encountered an issue with HTML content which seems to be escaped in the bsPopover function, see 

``` r
bsPopover("linkID", title="title", content="<b>Test</b>")
```

which results in 

``` javascript
<script>
$(document).ready(function() {
    setTimeout(function() {shinyBS.addTooltip('linkID', 'popover', 
    {'content': '&lt;b&gt;Test&lt;/b&gt;', 'placement': 'bottom', 'trigger': 'hover', 'title': 'title'}
    )}, 100) });
</script> 
```

Directly masking HTML does not work, either:

``` r
content=HTML("<b>Test</b>")
```

My current workaround is replacing the JavaScript code manually:

``` r
bsPopoverTag <- bsPopover("linkID", title="title", content="<b>Test</b>")
bsPopoverHTML <- HTML("$(document).ready(function() {setTimeout(function() { shinyBS.addTooltip('linkID', 'popover', {'content': '<b>Test</b>', 'placement': 'bottom', 'trigger': 'hover', 'title': 'title'})}, 100)});")
bsPopoverTag$children[[1]] <- bsPopoverHTML
```

Thanks
Alex

**Comment by ebailey78** [comment]
Thank you for bringing that to my attention. I thought I fixed that problem. HTML worked with `addPopover` from the server but not with `bsPopover` in the UI. I think it is fixed now. Let me know if you have any problems.

Thanks,

Eric

**Comment by akaever** [comment]
It works!

Thanks
Alex
