### ISSUE TITLE
suggestion: use display.mode = "showcase" in the examples

### ISSUE THREAD

**Issue by FrissAnalytics** [ebailey78/shinyBS#23]
Hi Eric,

while I was running through the shinyBS v5.0 code I thought it would be nice if the examples used:

``` r
    runApp("example",display.mode = "showcase")
```

now the users can see what you are able to do, but they cannot see all the code (at least not always directly). With showcase mode that is solved. 

best Herman

**Comment by ebailey78** [comment]
Good suggestion. I've implemented it. Thanks!
