### ISSUE TITLE
Collapse Panel defaults to closed regardless

### ISSUE THREAD

**Issue by erikwestlund** [ebailey78/shinyBS#24]
I want a single collapse panel, defaulting to open.

```
  bsCollapse(multiple = FALSE, open = "filters", id = "filterBar",
             bsCollapsePanel("Data Filter", "Cell treachery spearwife night's watch, tower suckling ...", id="filters", value="1"))
```

It loads but by default it's closed and the user must open it

**Comment by ebailey78** [comment]
`bsCollapsePanel` does not accept an `id` attribute. If you change to `value = "filters"` then it should work.

**Comment by erikwestlund** [comment]
I'll give it a shot... you may want to update your demo on the Spark page :)

[image: Inline image 1]

**Comment by ebailey78** [comment]
Unfortunately I didn't put that demo up, and I don't have any access to it... It is for a pre-bootstrap3 version of shinyBS. I didn't even realize that it was still there. I will try to contact the guy who put it up and see if he will take it down. Thanks.

**Comment by erikwestlund** [comment]
ah, sorry, i thought it was yours

**Comment by ebailey78** [comment]
Not a problem at all. Thanks for pointing it out. It explains some other questions I've gotten! I did make the demo but John Harrison posted it to spark. I just emailed him and asked him to remove it.Thanks again.

**Comment by johndharrison** [comment]
@ebailey78 I have taken down the demo for shinyBS bs2. Great package btw :thumbsup:

**Comment by ebailey78** [comment]
@johndharrison Thank you
