### ISSUE TITLE
customize bsModal footer

### ISSUE THREAD

**Issue by ebailey78** [ebailey78/shinyBS#25]
Make it possible to customize the elements present in the footer of the modal dialog created with bsModal.

**Comment by ebailey78** [comment]
Added a `footer` argument to `bsModal` that can accept additional elements for the footer and a `close.button` argument to turn current close button on/off.

**Comment by ghost** [comment]
how to use those though? I've tried several versions of input argument null, false, off for footer and close button but nothing. Could you provide an example how to do that, how to change the text of the close button, style of the title and such. Would be very helpful to a lot of interested users I think

**Comment by pmcharrison** [comment]
Agreed, footer customisation would be useful, but doesn't work for me. Looking at the source, it doesn't look as if any methods for footer customisation are implemented.

**Comment by tkrabel** [comment]
Footer customization doesn't work for me either. Would be very useful.

**Comment by czhang2718** [comment]
Has this been implemented?

**Comment by AARON-CLARK** [comment]
> Has this been implemented?

Hi, I'm also interested in if this feature is functional?
