### ISSUE TITLE
Width of popOver with placement="right"

### ISSUE THREAD

**Issue by tobiguennel** [ebailey78/shinyBS#32]
I added popOvers for two graphs located within the same shiny tabPanel. The popOver with placement specified as "left" shows up fine; however the width of the popOver with placement specified as "right" is too narrow making the popOver look odd as shown in the image below. This only happens for placement="right". If I used the same code and just change "right" to any other placement option, the popOver looks fine.

I can't share the entire code, but basically I just used:

``` R
 bsPopover("visid1",,title='<font size="4">Gene Expression Heatmap',content='Text to go into the popOver showing to the right of visual 1', placement="right",trigger="hover"),
 bsPopover("visid2",title='<font size="4">Gene Expression Heatmap',content='Text to go into the popOver showing to the left of visual 2', placement="left",trigger="hover"),
```

![image](https://cloud.githubusercontent.com/assets/11778069/7392470/ee73eaba-ee55-11e4-862b-2807b48238f5.png)

**Comment by ebailey78** [comment]
I think your problem can be fixed by adding `options = list(container = "body")` to your `bsPopover` call. So:

``` R
 bsPopover("visid1",title='<font size="4">Gene Expression Heatmap',content='Text to go into the popOver showing to the right of visual 1', placement="right",trigger="hover", options = list(container = "body"))
```

If that doesn't work let me know.

Thanks,

Eric

**Comment by bwaismeyer** [comment]
Noting that this fixed a similar issue for me (popover text was being compressed to the width of the column it was called in).

**Comment by tobiguennel** [comment]
This worked great. Thank you for the quick reply!
