### ISSUE TITLE
bsModal Integration with DT Events

### ISSUE THREAD

**Issue by DarioS** [ebailey78/shinyBS#45]
I would like to propose that `bsModal` can be associated with a data table. Currently, the `trigger` parameter requires "The id of a button or link". In my use case, I have a table of numbers, and when a cell of the table is clicked, a popup will show the scatterplot of the data used to calculate that number. I need to link the modal popup to the click information available from DT.

**Comment by shrektan** [comment]
I think you may realize your idea by observing the DT_row_selected?

发自我的 iPhone

**Comment by DarioS** [comment]
The suggestion does not work.

**Comment by mheiser-md** [comment]
Check my code in issue bsModal and dateinput #46. It shows an example how one can use the row_selected event to toggle a Modal.

**Comment by DarioS** [comment]
Having an event observer on the cell clicked event and toggling a modal is a correct approach.
