### ISSUE TITLE
bsModal and dateinput

### ISSUE THREAD

**Issue by Persedes** [ebailey78/shinyBS#46]
Hi there,

I am trying to add a dateinput to a bsModal, however the calendar widget is in the background/ behind the Modal and can not be used. Any ideas?

![image](https://cloud.githubusercontent.com/assets/13694813/9136504/5c7f1560-3d17-11e5-90db-fbf162c5b12a.png)

``` r
library(shiny)
library(shinyBS)

shinyApp(
  ui =fluidPage(
    mainPanel(
      dataTableOutput("x1"),
      bsModal("modalExample", "Data Table", "rowtogg", size = "large",
              dateInput("dates", "Enter date"))
    )
  ),



  server = function(input, output, session) {
    output$x1 <- renderDataTable({
      DT::datatable( data.frame(x = 1:4), selection = "single" )
    }, server = FALSE)

    observeEvent({
      input[[paste( "x1", "rows_selected", sep="_" )]]
    },{

      toggleModal(session, "modalExample", "open")
    })
  }
)
```

**Comment by mheiser-md** [comment]
Added this into the modal and it worked: (Thanks to Yenne Info at stackoverflow)

tags$style(
            type = "text/css", ".datepicker{z-index: 1100 !important;}")
