### ISSUE TITLE
alternative botton colors

### ISSUE THREAD

**Issue by topepo** [ebailey78/shinyBS#56]
I'm not sure if you are constrained to what style of buttons are available but it would be great to be able to use others colors for buttons besides the handful currently in the package.  

I don't see a way of adding that via css or anything but please let me know if I've missed it. 

Thanks,

Max

**Comment by haozhu233** [comment]
I don't think it's possible. This package is using bootstrap and bootstrap only have that many colors and styles. 

You can try to put the bootstrap css into the www folder and use base shiny to run it. You will have an easily accessible css file for you to edit and you can edit the color there by searching something like "text-primary"

**Comment by topepo** [comment]
Thanks.
