### ISSUE TITLE
popover width

### ISSUE THREAD

**Issue by user11287** [ebailey78/shinyBS#64]
Hey, 
I wouldn't call it an issue, just didn't figure out myself how to do it. If I make a popover with placement = "left" I get a nice fluffy popOver with enough place to write a decent help-text. However If I place it on the right the popover is a lot more tightier and a sentence with like 10 words takes 6 lines. Is this a desired effect, and if so how do I set a width for the popover, if I need it to go to the right.

Sorry for the retarded question.
Best regards, and great package!

**Comment by dominiqueemmanuel** [comment]
Hey,

I have tried theses options (width and maw-width)  :

`addPopover(session = session
             , id="id"
             ,title= "my title"
        , content = "my very long content..."
             ,placement = "bottom"
            , trigger = 'hover'
        , options = list(container = "body",width = "700px","max-width" = "700px"))
`

But it doesn't change de width of the popover. I don't know how to do it...
